language: java

jdk: oraclejdk8

install: "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -source 7"

git:
    submodules: false

# before_install:
#   - echo -e "machine bitbucket.org\n  login $BB_USER\n  password $BB_PASS" >> ~/.netrc
#   - git submodule update --init --recursive
